#!/usr/bin/env python3
"""
Analysis Report Generator

Formats analysis findings into structured markdown reports with diff suggestions.
Used by the agent after completing trace analysis.

USAGE:
    python report_generator.py \
        --symptom "output missing earnings data" \
        --category research_gap \
        --trace-id abc123 \
        --case-id 0001 \
        --root-cause "finnhub earnings endpoint not configured" \
        --evidence "Tool calls: perplexity (1), finnhub.quote (1), finnhub.earnings (0)"

OUTPUT:
    Structured markdown report to stdout
"""

import argparse
import sys
from datetime import datetime
from typing import Optional, List


def generate_report(
    symptom: str,
    category: str,
    trace_id: str,
    case_id: Optional[str],
    root_cause: str,
    evidence: Optional[str] = None,
    fixes: Optional[List[str]] = None,
) -> str:
    """Generate a structured analysis report."""

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Category display names
    category_names = {
        "research_gap": "Research Gap (Missing Data)",
        "style_mismatch": "Style Mismatch",
        "tool_selection": "Tool Selection Issue",
        "execution_error": "Execution Error",
        "latency": "Performance/Latency",
        "quality_general": "General Quality Issue",
        "cost": "Cost Optimization",
        "tool_utilization": "Tool Utilization",
    }

    category_display = category_names.get(category, category)

    report = f"""# Trace Analysis Report

**Generated:** {timestamp}

---

## Symptom

> {symptom}

| Field | Value |
|-------|-------|
| **Trace ID** | `{trace_id}` |
| **Case ID** | `{case_id or 'Not specified'}` |
| **Category** | {category_display} |

---

## Root Cause

{root_cause}

---

## Evidence

"""

    if evidence:
        report += f"""{evidence}

---

"""
    else:
        report += """*No evidence provided. Add with --evidence flag.*

---

"""

    report += """## Recommended Fixes

"""

    if fixes:
        for i, fix in enumerate(fixes, 1):
            report += f"""### Fix {i}

{fix}

"""
    else:
        report += """*No specific fixes provided. Add with --fix flag (can be used multiple times).*

---

## Verification Steps

After applying fixes:

1. Re-run workflow:
   ```bash
   python run_workflow.py --case {case_id} --topic "..."
   ```

2. Retrieve new trace:
   ```bash
   python3 trace_retriever.py --last 1 --case {case_id} --mode io
   ```

3. Verify the issue is resolved

""".format(case_id=case_id or "<case_id>")

    report += """---

*Report generated by langfuse-analyzer plugin*
"""

    return report


def generate_diff_suggestion(
    file_path: str,
    description: str,
    before_lines: List[str],
    after_lines: List[str],
    context_before: int = 1,
) -> str:
    """Generate a diff-style fix suggestion."""

    diff = f"""**File:** `{file_path}`

**Change:** {description}

```diff
"""

    # Add context lines (unchanged)
    for line in before_lines[:context_before]:
        diff += f" {line}\n"

    # Add removed lines
    for line in before_lines[context_before:]:
        diff += f"-{line}\n"

    # Add added lines
    for line in after_lines:
        diff += f"+{line}\n"

    diff += "```\n"

    return diff


def main():
    parser = argparse.ArgumentParser(
        description="Generate structured analysis reports",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        "--symptom",
        required=True,
        help="User's original problem description"
    )
    parser.add_argument(
        "--category",
        required=True,
        choices=[
            "research_gap", "style_mismatch", "tool_selection",
            "execution_error", "latency", "quality_general",
            "cost", "tool_utilization"
        ],
        help="Classified symptom category"
    )
    parser.add_argument(
        "--trace-id",
        required=True,
        help="Langfuse trace ID"
    )
    parser.add_argument(
        "--case-id",
        help="Writing ecosystem case ID"
    )
    parser.add_argument(
        "--root-cause",
        required=True,
        help="Identified root cause explanation"
    )
    parser.add_argument(
        "--evidence",
        help="Evidence supporting the root cause (markdown formatted)"
    )
    parser.add_argument(
        "--fix",
        action="append",
        dest="fixes",
        help="Recommended fix (can be used multiple times)"
    )

    args = parser.parse_args()

    report = generate_report(
        symptom=args.symptom,
        category=args.category,
        trace_id=args.trace_id,
        case_id=args.case_id,
        root_cause=args.root_cause,
        evidence=args.evidence,
        fixes=args.fixes,
    )

    print(report)


if __name__ == "__main__":
    main()
